src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * User
 *
 *
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User
{
    /**
     *@var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @var \DateTime|null
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_naissance;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $Role;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**

     * @ORM\OneToMany(targetEntity=Eleve::class, mappedBy="User")
     */
    private $eleves;

    /**
     *
     * @ORM\OneToMany(targetEntity=Commentaires::class, mappedBy="author")
     */
    private $commentaires;



    public function __construct()
    {
        $this->eleves = new ArrayCollection();
        $this->content = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->Role;
    }

    public function setRole(string $Role): self
    {
        $this->Role = $Role;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * @return Collection|Eleve[]
     */
    public function getEleves(): Collection
    {
        return $this->eleves;
    }

    public function addElefe(Eleve $elefe): self
    {
        if (!$this->eleves->contains($elefe)) {
            $this->eleves[] = $elefe;
            $elefe->setUser($this);
        }

        return $this;
    }

    public function removeElefe(Eleve $elefe): self
    {
        if ($this->eleves->removeElement($elefe)) {
            // set the owning side to null (unless already changed)
            if ($elefe->getUser() === $this) {
                $elefe->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commentaires[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaires $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setAuthor($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaires $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getAuthor() === $this) {
                $commentaire->setAuthor(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return  $this->getId().' '.$this->getNom().' '.$this->getAdresse().' '.$this->getEmail().' '.$this->getPassword().' '.$this->getPrenom().' '.$this->getRole().' '.$this->getCommentaires().' '.$this->getEleves();
    }

}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Nom')
            ->add('Prenom')
            ->add('email')
            ->add('dateNaissance' , BirthdayType::class,[
                'placeholder' => 'Select a value' ,
            ])
            ->add('password')
            ->add('Role',ChoiceType::class,[
                'label'=>'Role',
                'placeholder'=>'choose type:',
                'choices'=>[
                    'Etudient'=>'Etudient',
                    'Eleve'=>'Eleve',


                ],
            ])
            ->add('adresse')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;


use App\Entity\Club;
use App\Entity\User;
use App\Form\UserType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;




/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(Request $request): Response
    {
        $session = $request->getSession();
        $mavariable = $session->get('mavariable');
        if (isset($mavariable)) {
       //     echo 'ma session est deja ouverte '.$mavariable;
        } else {
            //echo 'nouvelle variable '.$mavariable;
//            $session->set('mavariable','name');

        }
        $users = $this->getDoctrine()
            ->getRepository(User::class)
            ->findAll();

        return $this->render('user/index.html.twig', [
            'users' => $users,

            ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/show/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/login", name="user_login")
     */
    public function login(Request $request): Response
    {
        $session = $request->getSession();
        $session->clear();
        $user = new User();
        $form = $this->createFormBuilder($user)
            ->add('Email')
            ->add('password', PasswordType::class)
            ->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $pwd = $user->getPassword();
            $email = $user->getEmail();
            dump($user);
            $repo = $this->getDoctrine()->getRepository(User::class);
            $user1 = $repo->findOneBy(['Email' => $email, 'password' => $pwd]);
            if (!$user1) {
                $this->get('session')->getFlashBag()->add(
                    'notice',
                    'Customer Added!'
                );
            } else {
                if (!$session->has('name')) {
                    $session->set('name', $user1->getNom());
                    $name = $session->get('name');
                    if ($user1->getRole() == "Admin") {
                        $user=$user1;

                        return $this->render('user/index.html.twig', [
                            'users' => $this->getDoctrine()->getRepository(User::class)->findAll(), 'name' => $name , 'user' => $user->getId()
                        ]);

                    } else if ($user1->getRole()=="Etudiant") {
                        $user=$user1;

                        return $this->redirectToRoute('welcome_Etud',['id'=>$user1->getId()]);


                    }else if ($user1->getRole() == "Eleve") {
                        $user=$user1;

                        return $this->redirectToRoute('eleve_new',['id'=> $user1->getId()]);
                    }else if ($user1->getRole() == "Etablissement") {
                        $user=$user1;

                        return $this->render('club/index.html.twig', [
                            'clubs' => $this->getDoctrine()->getRepository(Club::class)->findAll(), 'name' => $name, 'idUser' => $user->getId()
                        ]);
                    }
                }


            }
        }
        return $this->render('user/login.html.twig', [
            'user' => $user,
            'form' => $form->createView(),]);
    }

    /**
     * @Route("/edit/{id}", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('welcome_Etud', ['id' => $user->getId()]);

        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="user_delete", methods={"POST"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }

    /**
     * @Route("/tri", name="tri", methods={"GET"})
     */
    public function listuser()
    {
        $p = $this->getDoctrine()->getRepository(User::class)->getCustomInformations();
        $user = $this->getDoctrine()->getRepository(User::class)->findAll();
        return $this->render("user/index.html.twig", array('users' => $user, 'stat' => $p));

    }

    /**
     * @Route("/listtri/{id}", name="list_tri")
     */
    public function listTrierUser(User $user)

    {
        $p = $this->getDoctrine()->getRepository(User::class)->getCustomInformations();
        $user = $this->getDoctrine()->getRepository(User::class)->listOrderByName();
        return $this->render("user/index.html.twig",
            array('users' => $user, 'stat' => $p));

    }
    /**
     * @Route("/Etudiant/{id}", name="welcome_Etud")
     */
    public function welcomeEtud(User $user)

    {
        return $this->render("user/etudiant-index.html.twig",
            ['user' => $user ]);

    }



}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.getId()}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.getId()) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/etudiant-index.html.twig
{% extends 'basejdida.html.twig' %}

{% block title %}Etudiant Acceuil{% endblock %}
{% block test %}
    <li><a href="{{ path("user_edit",{'id':user.Id }) }}">Modifier Votre compte</a> </li>
    <li><a href="{{ path("Consulter_user",{'id_User':user.Id}) }}">Mes cours</a> </li>
    <li><a href="{{ path("book1_index",{'id':user.Id}) }}">bibliothèque</a></li>
    <li><a href="{{ path("article_etud",{'iduser':user.Id}) }}">Forum</a></li>
    <li><a href="{{ path("club_newindex",{'idUser':user.Id}) }}">Clubs</a></li>

{% endblock %}
{% block test1 %}
    <li><a href="{{ path("book1_mybib",{'id':user.Id}) }}">Ma bibliothèque</a></li>
{% endblock %}
{% block body %}
    <a href="{{ path('user_login') }}">logout</a>
    <h1>Bienvenue {{ user.Nom }} Votre id est {{ user.id }}</h1>
{% endblock %}

templates/user/index.html.twig
{% extends 'back_s.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <a href="{{('login/login') }}">Logout</a>
<h1> {{ app.session.get('mavariable') }}</h1>

    <div class="container">
        <div class="row">
            <div class="col-12">

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">IdUser</th>
                        <th scope="col">Nom</th>
                        <th scope="col">Prenom</th>
                        <th scope="col">Email</th>
                        <th scope="col">DateNaissance</th>
                        <th scope="col">Password</th>
                        <th scope="col">Role</th>
                        <th scope="col">Addresse</th>
                        <a href="{{ path('tri' ) }}" class="accordion">Sort</a>



                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <td>{{ user.Id }}</td>
                            <td>{{ user.nom }}</td>
                            <td>{{ user.prenom }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.dateNaissance ? user.dateNaissance|date('Y-m-d') : '' }}</td>
                            <td>{{ user.password }}</td>
                            <td>{{ user.role }}</td>
                            <td>{{ user.adresse }}</td>
                            <td>
                                <a href="{{ path('user_new', {'idUser': user.Id}) }}" class="btn btn-dark">Add</a>
                                <a href="{{ path('user_show', {'id': user.Id}) }}" class="btn btn-primary">Show</a>
                                <a href="{{ path('user_edit', {'id': user.Id}) }}" class="btn btn-success">Edit</a>
                                <a href="{{ path('user_edit', {'id': user.Id}) }}" class="btn btn-danger">Delete</a>

                            </td>
                        </tr>
                    {% else %}

                    {% endfor %}

                    </td>

                    </tr>


                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <a href="{{ path('categorie_index') }}" class="btn btn-dark">Add</a>
{% endblock %}

templates/user/inscription.html.twig
{% extends 'base.html.twig' %}

{% block title %}aaaaaaaaaaa{% endblock %}

{% block body %}
    <h1>aaaaaaaaa</h1>

    {{ include('user/inscription.html.twig') }}

    <a href="{{ path('user_new') }}">back to list</a>
{% endblock %}

templates/user/login.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <body>
    <form class="form-signin"></form>
    <div class="center">
        <div class="container">
            <h2 class="form-signin-heading">Please login</h2>

            <form method="post">
                <div class="data">
                    <label>Email </label>
                    {{ form_widget(form.Email) }}
                </div>
                <div class="data">
                    <label>Password</label>
                    {{ form_widget(form.password) }}
                </div>
                <div class="forgot-pass">
                    <a href="#">Forgot Password?</a></div>
                <div class="btn">
                    <div class="inner">
                    </div>
                    <button type="submit">login</button>
                </div>
                <div class="signup-link">
                    Not a member? <a href="../user/new">Signup now</a></div>

            </form>
        </div>
    </div>
    </body>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% endblock %}

{% block body %}
    <h1>Create new Account</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>IdUser</th>
                <td>{{ user.idUser }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ user.prenom }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>DateNaissance</th>
                <td>{{ user.dateNaissance ? user.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Role</th>
                <td>{{ user.role }}</td>
            </tr>
            <tr>
                <th>Addresse</th>
                <td>{{ user.addresse }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">back to list</a>

    <a href="{{ path('user_edit', {'idUser': user.idUser}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}